import 'package:flutter/material.dart';

import '../../data/honeychain_store.dart';
import '../../services/platform_api_service.dart';
import '../../theme/app_theme.dart';
import '../../widgets/status_pill.dart';
import 'platform_org_detail_screen.dart';

/// Platform Oversight -> Organizations.
///
/// Full FPO lifecycle: list every organization, create a new one (server-side
/// `organization_key` is generated by the backend), and open the detail view
/// for lifecycle + membership governance. Empty/error states are explicit and
/// never filled with fabricated rows.
class PlatformOrganizationsScreen extends StatefulWidget {
  const PlatformOrganizationsScreen({super.key});

  @override
  State<PlatformOrganizationsScreen> createState() =>
      _PlatformOrganizationsScreenState();
}

class _PlatformOrganizationsScreenState
    extends State<PlatformOrganizationsScreen> {
  List<PlatformOrganization>? _orgs;
  String? _error;
  bool _busy = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final store = HoneyChainStore.instance;
    if (_busy) return;
    setState(() {
      _busy = true;
      _error = null;
    });
    try {
      final orgs = await store.platformApi.listOrganizations();
      if (!mounted) return;
      setState(() => _orgs = orgs);
    } on Exception catch (e) {
      if (!mounted) return;
      setState(() => _error = e.toString());
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  Future<void> _createOrg() async {
    final created = await showModalBottomSheet<PlatformOrganization>(
      context: context,
      backgroundColor: AppTheme.bg,
      showDragHandle: true,
      isScrollControlled: true,
      builder: (_) => const _CreateOrgSheet(),
    );
    if (created == null || !mounted) return;
    setState(() {
      _orgs = [...?_orgs, created];
    });
    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(SnackBar(
        content: Text('Created ${created.name} (${created.organizationKey})'),
        backgroundColor: AppTheme.honeyDark,
        behavior: SnackBarBehavior.floating,
      ));
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: RefreshIndicator(
        onRefresh: _load,
        child: ListView(
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
          children: [
            Row(
              children: [
                const Expanded(
                  child: Text(
                    'Organizations',
                    style: TextStyle(
                      fontSize: 22,
                      fontWeight: FontWeight.w800,
                      color: AppTheme.ink,
                    ),
                  ),
                ),
                IconButton(
                  onPressed: _busy ? null : _load,
                  icon: _busy
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(strokeWidth: 2),
                        )
                      : const Icon(Icons.refresh_rounded, size: 22),
                  tooltip: 'Refresh organizations',
                ),
                const SizedBox(width: 4),
                IconButton(
                  onPressed: _createOrg,
                  icon: const Icon(Icons.add_circle_outline_rounded, size: 24, color: AppTheme.honeyDark),
                  tooltip: 'Create organization',
                ),
              ],
            ),
            const SizedBox(height: 4),
            Text(
              'Register an FPO or open one to manage membership.',
              style: const TextStyle(fontSize: 13, color: AppTheme.inkSoft),
            ),
            const SizedBox(height: 16),
            if (_error != null)
              _ErrorCard(message: _error!, onRetry: _load)
            else if (_orgs == null)
              const Padding(
                padding: EdgeInsets.symmetric(vertical: 60),
                child: Center(child: CircularProgressIndicator()),
              )
            else if (_orgs!.isEmpty)
              const _EmptyCard(text: 'No organizations registered yet.')
            else ...[
              for (final org in _orgs!) ...[
                _OrgCard(
                  org: org,
                  onTap: () async {
                    await Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (_) => PlatformOrgDetailScreen(org: org),
                      ),
                    );
                    _load();
                  },
                ),
                const SizedBox(height: 10),
              ],
            ],
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }
}

class _OrgCard extends StatelessWidget {
  const _OrgCard({required this.org, required this.onTap});

  final PlatformOrganization org;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final statusColor = switch (org.status) {
      'ACTIVE' => AppTheme.green,
      'SUSPENDED' => AppTheme.orange,
      'DORMANT' => AppTheme.red,
      _ => AppTheme.grey,
    };
    return Material(
      color: AppTheme.card,
      borderRadius: BorderRadius.circular(16),
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(16),
        child: Container(
          padding: const EdgeInsets.all(14),
          decoration: BoxDecoration(
            border: Border.all(color: AppTheme.border),
            borderRadius: BorderRadius.circular(16),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      color: AppTheme.honey.withValues(alpha: 0.16),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Icon(Icons.storefront_outlined,
                        color: AppTheme.honeyDark, size: 22),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          org.name,
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: const TextStyle(
                            fontSize: 15,
                            fontWeight: FontWeight.w800,
                            color: AppTheme.ink,
                          ),
                        ),
                        Text(
                          org.organizationKey,
                          style: const TextStyle(
                            fontSize: 12,
                            color: AppTheme.inkFaint,
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ),
                  StatusPill(label: org.status, color: statusColor),
                  const SizedBox(width: 4),
                  const Icon(Icons.chevron_right_rounded,
                      color: AppTheme.inkFaint, size: 20),
                ],
              ),
              if (org.location.isNotEmpty || org.state.isNotEmpty) ...[
                const SizedBox(height: 8),
                Text(
                  [org.district, org.state, org.country]
                      .where((s) => s.isNotEmpty)
                      .join(' · '),
                  style: const TextStyle(fontSize: 12, color: AppTheme.inkFaint),
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}

class _CreateOrgSheet extends StatefulWidget {
  const _CreateOrgSheet();

  @override
  State<_CreateOrgSheet> createState() => _CreateOrgSheetState();
}

class _CreateOrgSheetState extends State<_CreateOrgSheet> {
  final _name = TextEditingController();
  final _email = TextEditingController();
  final _phone = TextEditingController();
  bool _busy = false;

  @override
  void dispose() {
    _name.dispose();
    _email.dispose();
    _phone.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    final name = _name.text.trim();
    if (name.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Organization name is required')),
      );
      return;
    }
    setState(() => _busy = true);
    try {
      final org = await HoneyChainStore.instance.platformApi.createOrganization(
        name: name,
        contactEmail: _email.text.trim(),
        contactPhone: _phone.text.trim(),
      );
      if (!mounted) return;
      Navigator.of(context).pop((org));
    } on Exception catch (e) {
      if (!mounted) return;
      setState(() => _busy = false);
      final message = e.toString().replaceFirst('Exception: ', '');
      ScaffoldMessenger.of(context)
        ..hideCurrentSnackBar()
        ..showSnackBar(SnackBar(content: Text(message)));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        left: 20,
        right: 20,
        top: 8,
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Create organization',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.w800,
              color: AppTheme.ink,
            ),
          ),
          const SizedBox(height: 4),
          const Text(
            'The backend generates the organization key; the new FPO starts as PENDING.',
            style: TextStyle(fontSize: 12.5, color: AppTheme.inkSoft, height: 1.35),
          ),
          const SizedBox(height: 18),
          TextField(
            controller: _name,
            textCapitalization: TextCapitalization.words,
            decoration: const InputDecoration(
              labelText: 'Organization name *',
              hintText: 'Nilgiris Honey FPO',
              prefixIcon: Icon(Icons.storefront_outlined, size: 20),
            ),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _email,
            keyboardType: TextInputType.emailAddress,
            decoration: const InputDecoration(
              labelText: 'Contact email',
              prefixIcon: Icon(Icons.mail_outline, size: 20),
            ),
          ),
          const SizedBox(height: 12),
          TextField(
            controller: _phone,
            keyboardType: TextInputType.phone,
            decoration: const InputDecoration(
              labelText: 'Contact phone',
              prefixIcon: Icon(Icons.phone_outlined, size: 20),
            ),
          ),
          const SizedBox(height: 22),
          SizedBox(
            height: 52,
            child: FilledButton.icon(
              onPressed: _busy ? null : _submit,
              icon: _busy
                  ? const SizedBox(
                      width: 18,
                      height: 18,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: AppTheme.ink,
                      ),
                    )
                  : const Icon(Icons.add_rounded, size: 20),
              label: Text(_busy ? 'Creating…' : 'Create organization'),
            ),
          ),
        ],
      ),
    );
  }
}

class _ErrorCard extends StatelessWidget {
  const _ErrorCard({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppTheme.redSoft,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.red.withValues(alpha: 0.4)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.error_outline, color: AppTheme.red, size: 20),
              const SizedBox(width: 8),
              const Expanded(
                child: Text(
                  'Could not load organizations',
                  style: TextStyle(fontWeight: FontWeight.w800, color: AppTheme.ink),
                ),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Text(
            message,
            style: const TextStyle(fontSize: 12.5, color: AppTheme.inkSoft, height: 1.35),
          ),
          const SizedBox(height: 10),
          OutlinedButton.icon(
            onPressed: onRetry,
            style: OutlinedButton.styleFrom(minimumSize: const Size(0, 40)),
            icon: const Icon(Icons.refresh_rounded, size: 18),
            label: const Text('Retry'),
          ),
        ],
      ),
    );
  }
}

class _EmptyCard extends StatelessWidget {
  const _EmptyCard({required this.text});

  final String text;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppTheme.card,
        borderRadius: AppTheme.radiusCard,
        border: Border.all(color: AppTheme.border),
      ),
      child: Text(
        text,
        textAlign: TextAlign.center,
        style: const TextStyle(fontSize: 13, color: AppTheme.inkSoft),
      ),
    );
  }
}