// AUTO-GENERATED by ml/train.py — DO NOT EDIT BY HAND.
//
// Lightweight offline Decision Tree exported from a DecisionTreeClassifier
// trained on the SYNTHETIC_PROTOTYPE demo dataset
// (ml/data/honeychain_bee_health_final_demo_dataset.csv).
//
// DATA HONESTY: This is a DEMO / PROTOTYPE screening artifact. It is
// NOT clinically validated and must never be presented as a diagnosis
// or as a real-world trained model.
//
// dataset_size     : 40
// dataset_hash     : e8dd57da9af65307
// data_type        : SYNTHETIC_PROTOTYPE
// generated_at     : 2026-08-31T07:30:33Z
// max_depth_chosen : None
// model_type       : DecisionTreeClassifier

/// Feature IDs in the exact training order (see BeeHealthFeature ids).
const List<String> kBeeHealthFeatureOrder = [
  'brood_spotted_comb',
  'brood_larvae_yellow_curled',
  'brood_sour_odor',
  'adult_crawling_unable_to_fly',
  'adult_k_wing',
  'adult_scattered_clusters',
  'adult_yellow_fecal_spots',
  'adult_swollen_black_abdomen',
];

/// Class labels in the exact training order (index == predict output).
const List<String> kBeeHealthClassLabels = [
  'EFB',
  'Acarine',
  'Nosema',
  'Healthy',
  'Unknown',
];

/// Node arrays, one per tree node (preorder as exported by sklearn).
/// A split node has feature >= 0; a leaf has feature = -1.
const List<int> kBeeHealthTreeFeature = [
  6,
  4,
  1,
  5,
  -1,
  0,
  5,
  3,
  -1,
  -1,
  -1,
  3,
  -1,
  -1,
  -1,
  5,
  5,
  -1,
  3,
  -1,
  -1,
  -1,
  -1,
];

const List<double> kBeeHealthTreeThreshold = [
  0.5,
  0.5,
  0.5,
  -0.5,
  -2.0,
  0.5,
  0.5,
  0.5,
  -2.0,
  -2.0,
  -2.0,
  0.5,
  -2.0,
  -2.0,
  -2.0,
  0.5,
  -0.5,
  -2.0,
  0.5,
  -2.0,
  -2.0,
  -2.0,
  -2.0,
];

const List<int> kBeeHealthTreeLeft = [
  1,
  2,
  3,
  4,
  -1,
  6,
  7,
  8,
  -1,
  -1,
  -1,
  12,
  -1,
  -1,
  -1,
  16,
  17,
  -1,
  19,
  -1,
  -1,
  -1,
  -1,
];

const List<int> kBeeHealthTreeRight = [
  22,
  15,
  14,
  5,
  -1,
  11,
  10,
  9,
  -1,
  -1,
  -1,
  13,
  -1,
  -1,
  -1,
  21,
  18,
  -1,
  20,
  -1,
  -1,
  -1,
  -1,
];

/// Leaf class index (index into kBeeHealthClassLabels), or -1 for splits.
const List<int> kBeeHealthTreeLeafClass = [
  -1,
  -1,
  -1,
  -1,
  4,
  -1,
  -1,
  -1,
  3,
  4,
  4,
  -1,
  0,
  4,
  0,
  -1,
  -1,
  1,
  -1,
  1,
  1,
  1,
  2,
];

/// Training majority share at this node (only meaningful for leaves).
const List<double> kBeeHealthTreeLeafPurity = [
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.0,
  0.0,
  1.0,
  1.0,
  1.0,
  0.0,
  1.0,
  1.0,
  1.0,
  0.0,
  0.0,
  1.0,
  0.0,
  1.0,
  0.5,
  1.0,
  1.0,
];

/// Number of training samples that reached each node.
const List<int> kBeeHealthTreeNodeSamples = [
  40,
  31,
  21,
  13,
  3,
  10,
  7,
  6,
  5,
  1,
  1,
  3,
  2,
  1,
  8,
  10,
  4,
  1,
  3,
  1,
  2,
  6,
  9,
];

/// Training-class sample counts at each node (rows = node, cols = class).
const List<List<int>> kBeeHealthTreeNodeVotes = [
  [10, 9, 9, 5, 7],
  [10, 9, 0, 5, 7],
  [10, 0, 0, 5, 6],
  [2, 0, 0, 5, 6],
  [0, 0, 0, 0, 3],
  [2, 0, 0, 5, 3],
  [0, 0, 0, 5, 2],
  [0, 0, 0, 5, 1],
  [0, 0, 0, 5, 0],
  [0, 0, 0, 0, 1],
  [0, 0, 0, 0, 1],
  [2, 0, 0, 0, 1],
  [2, 0, 0, 0, 0],
  [0, 0, 0, 0, 1],
  [8, 0, 0, 0, 0],
  [0, 9, 0, 0, 1],
  [0, 3, 0, 0, 1],
  [0, 1, 0, 0, 0],
  [0, 2, 0, 0, 1],
  [0, 1, 0, 0, 0],
  [0, 1, 0, 0, 1],
  [0, 6, 0, 0, 0],
  [0, 0, 9, 0, 0],
];
