/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as WorkspaceAdminRouteImport } from './routes/_workspace/admin'
import { Route as WorkspaceAlertsRouteImport } from './routes/_workspace/alerts'
import { Route as WorkspaceAskMyBeeRouteImport } from './routes/_workspace/ask-my-bee'
import { Route as WorkspaceBeekeeperRouteImport } from './routes/_workspace/beekeeper'
import { Route as WorkspaceBuyerRouteImport } from './routes/_workspace/buyer'
import { Route as WorkspaceKvicRouteImport } from './routes/_workspace/kvic'
import { Route as WorkspaceLabRouteImport } from './routes/_workspace/lab'
import { Route as WorkspaceOrgRouteImport } from './routes/_workspace/org'
import { Route as WorkspacePortalsRouteImport } from './routes/_workspace/portals'
import { Route as WorkspaceProcessorRouteImport } from './routes/_workspace/processor'
import { Route as PassportCodeRouteImport } from './routes/passport.$code'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as WorkspaceAdminPlatformRouteImport } from './routes/_workspace/admin.platform'
import { Route as WorkspaceBatchesBatchIdRouteImport } from './routes/_workspace/batches.$batchId'
import { Route as WorkspaceKvicOrgIdRouteImport } from './routes/_workspace/kvic.$orgId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAdminRoute = WorkspaceAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAlertsRoute = WorkspaceAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAskMyBeeRoute = WorkspaceAskMyBeeRouteImport.update({
  id: '/ask-my-bee',
  path: '/ask-my-bee',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBeekeeperRoute = WorkspaceBeekeeperRouteImport.update({
  id: '/beekeeper',
  path: '/beekeeper',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBuyerRoute = WorkspaceBuyerRouteImport.update({
  id: '/buyer',
  path: '/buyer',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceKvicRoute = WorkspaceKvicRouteImport.update({
  id: '/kvic',
  path: '/kvic',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLabRoute = WorkspaceLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceOrgRoute = WorkspaceOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePortalsRoute = WorkspacePortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProcessorRoute = WorkspaceProcessorRouteImport.update({
  id: '/processor',
  path: '/processor',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PassportCodeRoute = PassportCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => PassportRoute,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => VerifyRoute,
} as any)
const WorkspaceAdminPlatformRoute = WorkspaceAdminPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => WorkspaceAdminRoute,
} as any)
const WorkspaceBatchesBatchIdRoute = WorkspaceBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceKvicOrgIdRoute = WorkspaceKvicOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => WorkspaceKvicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/passport': typeof PassportRouteWithChildren
  '/verify': typeof VerifyRouteWithChildren
  '/admin': typeof WorkspaceAdminRouteWithChildren
  '/alerts': typeof WorkspaceAlertsRoute
  '/ask-my-bee': typeof WorkspaceAskMyBeeRoute
  '/beekeeper': typeof WorkspaceBeekeeperRoute
  '/buyer': typeof WorkspaceBuyerRoute
  '/kvic': typeof WorkspaceKvicRouteWithChildren
  '/lab': typeof WorkspaceLabRoute
  '/org': typeof WorkspaceOrgRoute
  '/portals': typeof WorkspacePortalsRoute
  '/processor': typeof WorkspaceProcessorRoute
  '/passport/$code': typeof PassportCodeRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/platform': typeof WorkspaceAdminPlatformRoute
  '/batches/$batchId': typeof WorkspaceBatchesBatchIdRoute
  '/kvic/$orgId': typeof WorkspaceKvicOrgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/passport': typeof PassportRouteWithChildren
  '/verify': typeof VerifyRouteWithChildren
  '/admin': typeof WorkspaceAdminRouteWithChildren
  '/alerts': typeof WorkspaceAlertsRoute
  '/ask-my-bee': typeof WorkspaceAskMyBeeRoute
  '/beekeeper': typeof WorkspaceBeekeeperRoute
  '/buyer': typeof WorkspaceBuyerRoute
  '/kvic': typeof WorkspaceKvicRouteWithChildren
  '/lab': typeof WorkspaceLabRoute
  '/org': typeof WorkspaceOrgRoute
  '/portals': typeof WorkspacePortalsRoute
  '/processor': typeof WorkspaceProcessorRoute
  '/passport/$code': typeof PassportCodeRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/admin/platform': typeof WorkspaceAdminPlatformRoute
  '/batches/$batchId': typeof WorkspaceBatchesBatchIdRoute
  '/kvic/$orgId': typeof WorkspaceKvicOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/passport': typeof PassportRouteWithChildren
  '/verify': typeof VerifyRouteWithChildren
  '/_workspace/admin': typeof WorkspaceAdminRouteWithChildren
  '/_workspace/alerts': typeof WorkspaceAlertsRoute
  '/_workspace/ask-my-bee': typeof WorkspaceAskMyBeeRoute
  '/_workspace/beekeeper': typeof WorkspaceBeekeeperRoute
  '/_workspace/buyer': typeof WorkspaceBuyerRoute
  '/_workspace/kvic': typeof WorkspaceKvicRouteWithChildren
  '/_workspace/lab': typeof WorkspaceLabRoute
  '/_workspace/org': typeof WorkspaceOrgRoute
  '/_workspace/portals': typeof WorkspacePortalsRoute
  '/_workspace/processor': typeof WorkspaceProcessorRoute
  '/passport/$code': typeof PassportCodeRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/_workspace/admin/platform': typeof WorkspaceAdminPlatformRoute
  '/_workspace/batches/$batchId': typeof WorkspaceBatchesBatchIdRoute
  '/_workspace/kvic/$orgId': typeof WorkspaceKvicOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/passport'
    | '/verify'
    | '/admin'
    | '/alerts'
    | '/ask-my-bee'
    | '/beekeeper'
    | '/buyer'
    | '/kvic'
    | '/lab'
    | '/org'
    | '/portals'
    | '/processor'
    | '/passport/$code'
    | '/verify/$code'
    | '/admin/platform'
    | '/batches/$batchId'
    | '/kvic/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/passport'
    | '/verify'
    | '/admin'
    | '/alerts'
    | '/ask-my-bee'
    | '/beekeeper'
    | '/buyer'
    | '/kvic'
    | '/lab'
    | '/org'
    | '/portals'
    | '/processor'
    | '/passport/$code'
    | '/verify/$code'
    | '/admin/platform'
    | '/batches/$batchId'
    | '/kvic/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/passport'
    | '/verify'
    | '/_workspace/admin'
    | '/_workspace/alerts'
    | '/_workspace/ask-my-bee'
    | '/_workspace/beekeeper'
    | '/_workspace/buyer'
    | '/_workspace/kvic'
    | '/_workspace/lab'
    | '/_workspace/org'
    | '/_workspace/portals'
    | '/_workspace/processor'
    | '/passport/$code'
    | '/verify/$code'
    | '/_workspace/admin/platform'
    | '/_workspace/batches/$batchId'
    | '/_workspace/kvic/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
  PassportRoute: typeof PassportRouteWithChildren
  VerifyRoute: typeof VerifyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/admin': {
      id: '/_workspace/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof WorkspaceAdminRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/alerts': {
      id: '/_workspace/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof WorkspaceAlertsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/ask-my-bee': {
      id: '/_workspace/ask-my-bee'
      path: '/ask-my-bee'
      fullPath: '/ask-my-bee'
      preLoaderRoute: typeof WorkspaceAskMyBeeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/beekeeper': {
      id: '/_workspace/beekeeper'
      path: '/beekeeper'
      fullPath: '/beekeeper'
      preLoaderRoute: typeof WorkspaceBeekeeperRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/buyer': {
      id: '/_workspace/buyer'
      path: '/buyer'
      fullPath: '/buyer'
      preLoaderRoute: typeof WorkspaceBuyerRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/kvic': {
      id: '/_workspace/kvic'
      path: '/kvic'
      fullPath: '/kvic'
      preLoaderRoute: typeof WorkspaceKvicRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/lab': {
      id: '/_workspace/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof WorkspaceLabRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/org': {
      id: '/_workspace/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof WorkspaceOrgRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/portals': {
      id: '/_workspace/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof WorkspacePortalsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/processor': {
      id: '/_workspace/processor'
      path: '/processor'
      fullPath: '/processor'
      preLoaderRoute: typeof WorkspaceProcessorRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/passport/$code': {
      id: '/passport/$code'
      path: '/$code'
      fullPath: '/passport/$code'
      preLoaderRoute: typeof PassportCodeRouteImport
      parentRoute: typeof PassportRoute
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/_workspace/admin/platform': {
      id: '/_workspace/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof WorkspaceAdminPlatformRouteImport
      parentRoute: typeof WorkspaceAdminRoute
    }
    '/_workspace/batches/$batchId': {
      id: '/_workspace/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof WorkspaceBatchesBatchIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/kvic/$orgId': {
      id: '/_workspace/kvic/$orgId'
      path: '/$orgId'
      fullPath: '/kvic/$orgId'
      preLoaderRoute: typeof WorkspaceKvicOrgIdRouteImport
      parentRoute: typeof WorkspaceKvicRoute
    }
  }
}

interface WorkspaceAdminRouteChildren {
  WorkspaceAdminPlatformRoute: typeof WorkspaceAdminPlatformRoute
}

const WorkspaceAdminRouteChildren: WorkspaceAdminRouteChildren = {
  WorkspaceAdminPlatformRoute: WorkspaceAdminPlatformRoute,
}

const WorkspaceAdminRouteWithChildren = WorkspaceAdminRoute._addFileChildren(
  WorkspaceAdminRouteChildren,
)

interface WorkspaceKvicRouteChildren {
  WorkspaceKvicOrgIdRoute: typeof WorkspaceKvicOrgIdRoute
}

const WorkspaceKvicRouteChildren: WorkspaceKvicRouteChildren = {
  WorkspaceKvicOrgIdRoute: WorkspaceKvicOrgIdRoute,
}

const WorkspaceKvicRouteWithChildren = WorkspaceKvicRoute._addFileChildren(
  WorkspaceKvicRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceAdminRoute: typeof WorkspaceAdminRouteWithChildren
  WorkspaceAlertsRoute: typeof WorkspaceAlertsRoute
  WorkspaceAskMyBeeRoute: typeof WorkspaceAskMyBeeRoute
  WorkspaceBeekeeperRoute: typeof WorkspaceBeekeeperRoute
  WorkspaceBuyerRoute: typeof WorkspaceBuyerRoute
  WorkspaceKvicRoute: typeof WorkspaceKvicRouteWithChildren
  WorkspaceLabRoute: typeof WorkspaceLabRoute
  WorkspaceOrgRoute: typeof WorkspaceOrgRoute
  WorkspacePortalsRoute: typeof WorkspacePortalsRoute
  WorkspaceProcessorRoute: typeof WorkspaceProcessorRoute
  WorkspaceBatchesBatchIdRoute: typeof WorkspaceBatchesBatchIdRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAdminRoute: WorkspaceAdminRouteWithChildren,
  WorkspaceAlertsRoute: WorkspaceAlertsRoute,
  WorkspaceAskMyBeeRoute: WorkspaceAskMyBeeRoute,
  WorkspaceBeekeeperRoute: WorkspaceBeekeeperRoute,
  WorkspaceBuyerRoute: WorkspaceBuyerRoute,
  WorkspaceKvicRoute: WorkspaceKvicRouteWithChildren,
  WorkspaceLabRoute: WorkspaceLabRoute,
  WorkspaceOrgRoute: WorkspaceOrgRoute,
  WorkspacePortalsRoute: WorkspacePortalsRoute,
  WorkspaceProcessorRoute: WorkspaceProcessorRoute,
  WorkspaceBatchesBatchIdRoute: WorkspaceBatchesBatchIdRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

interface PassportRouteChildren {
  PassportCodeRoute: typeof PassportCodeRoute
}

const PassportRouteChildren: PassportRouteChildren = {
  PassportCodeRoute: PassportCodeRoute,
}

const PassportRouteWithChildren = PassportRoute._addFileChildren(
  PassportRouteChildren,
)

interface VerifyRouteChildren {
  VerifyCodeRoute: typeof VerifyCodeRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyCodeRoute: VerifyCodeRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
  PassportRoute: PassportRouteWithChildren,
  VerifyRoute: VerifyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
