-- Organization identity (10) — rewritten.
--
-- Supersedes the earlier draft that widened `organizations.id` from uuid to
-- text. `organizations.id` STAYS uuid: it is the primary key every existing FK
-- graph (`profiles`, `beekeepers`, `batches`) hangs off, and the backend's
-- record ids are uuids. Widening it to text was the wrong call.
--
-- This migration instead introduces the human-readable organisation key
-- `organization_key` (ORG-000001, ORG-000002, ...) as a separate, unique,
-- NOT NULL column. Keys are generated by the backend from a Postgres sequence
-- (see migration 011) and must never be derived from state/district/name or
-- any other geolocation — the platform key survives renames and relocations.
--
-- Also applied here: migration 009 (`beekeepers.producer_id`), which the live
-- project had not yet received and which backend beekeeper registration needs.
--
-- Additive + idempotent: no row is dropped, widened or renamed. The existing
-- live organizations keep their uuid ids and data; each gets a deterministic
-- backfilled key ordered by creation.

alter table organizations add column if not exists organization_key text;

-- Backfill deterministic keys for every existing row (by creation order).
do $$
declare
  r record;
  n int := 0;
begin
  for r in
    select id from organizations
    where organization_key is null or organization_key = ''
    order by created_at, id
  loop
    n := n + 1;
    update organizations
       set organization_key = 'ORG-' || lpad(n::text, 6, '0')
     where id = r.id
       and (organization_key is null or organization_key = '');
  end loop;
end $$;

alter table organizations alter column organization_key set not null;
alter table organizations add constraint uq_organizations_organization_key
  unique (organization_key);

-- Organization lifecycle status. Existing rows were already operating, so they
-- become ACTIVE; newly platform-created orgs are created PENDING in code.
alter table organizations add column if not exists status text not null default 'ACTIVE';
alter table organizations add constraint chk_organizations_status
  check (status in ('PENDING', 'ACTIVE', 'SUSPENDED', 'DORMANT'));

-- Location / contact / registration metadata. Never part of the key.
alter table organizations add column if not exists country text;
alter table organizations add column if not exists state text;
alter table organizations add column if not exists district text;
alter table organizations add column if not exists address text;
alter table organizations add column if not exists postal_code text;
alter table organizations add column if not exists contact_email text;
alter table organizations add column if not exists contact_phone text;
alter table organizations add column if not exists registration_no text;

-- Beekeeper Producer ID (previously migration 009). The live project never
-- received 009; folding it in here lets a single migration bring the schema
-- current.
alter table beekeepers add column if not exists producer_id text not null default '';
create index if not exists idx_beekeepers_producer_id on beekeepers(producer_id);